version: '2.2'
services:
    payara:
        image: payara/server-full:5.2022.2
        ports:
         - "58080:8080"
         - "58443:8443"
         - "54848:4848"
         - "59009:9009"
        environment:
          - PAYARA_ARGS=--debug
    db:
        image: postgres:9.6-alpine
        environment:
        - POSTGRES_PASSWORD=database
        - POSTGRES_USER=database
        - POSTGRES_DB=database
        ports:
        - "55432:5432"
        volumes:
        - test-db-data:/var/lib/postgresql/data
volumes:
  test-db-data:

